apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80        # Exposed port
      targetPort: 8080 # Port on the container
  type: LoadBalancer